name 'openshift-openshift_origin'
version '4.0.10'
author 'Mojo Lingo, Red Hat'
license 'ASL'
project_page 'https://github.com/openshift/puppet-openshift_origin'
source 'git://github.com/openshift/puppet-openshift_origin.git'
summary 'Module for installing Red Hat Openshift'
description 'Configures OpenShift Origin broker, nodes and support servers'
dependency 'rharrison/lokkit', '>=0.2.0'
dependency 'puppetlabs/ntp', '>=0.1.0'
dependency 'puppetlabs/stdlib', '>=2.6.0'
dependency 'blentz/selinux_types', '>=0.1.0'
dependency 'puppetlabs/haproxy', '>=0.4.1'
dependency 'arioch/keepalived', '>=0.0.10'
dependency 'duritong/sysctl', '>=0.0.1'
